# Generated by Django 6.0.2 on 2026-02-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativas'},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
    ]
