# Generated by Django 6.0.2 on 2026-02-23 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equetes', '0002_alter_alternativa_options_alter_questao_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='minhas_questoes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
