# Generated by Django 6.0.2 on 2026-02-23 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equetes', '0003_questao_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativa',
            name='votos',
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_voto', models.DateTimeField(auto_now_add=True)),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equetes.alternativa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equetes.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'questao')},
            },
        ),
    ]
